# Generated by Django 3.2.25 on 2026-03-07 11:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=60)),
                ('max_numb_students', models.CharField(blank=True, default='', max_length=65)),
                ('hours_per_week', models.IntegerField(default=0, help_text='Contact hours per week', validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.IntegerField(default=3, help_text='Lower = scheduled earlier')),
                ('max_continuous_hours', models.IntegerField(default=2, help_text='Max consecutive hours per day', validators=[django.core.validators.MinValueValidator(1)])),
                ('course_type', models.CharField(choices=[('THEORY', 'Theory'), ('LAB', 'Lab'), ('ELECTIVE', 'Elective')], default='THEORY', max_length=10)),
                ('split_into_batches', models.BooleanField(default=False, help_text='Divide section into B1/B2 batches for this lab')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('fitness_score', models.FloatField(default=0.0)),
                ('generation_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LabRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('pid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('time', models.CharField(choices=[('8:45 - 9:45', '8:45 - 9:45'), ('9:45 - 10:35', '9:45 - 10:35'), ('10:35 - 11:25', '10:35 - 11:25'), ('11:25 - 12:15', '11:25 - 12:15'), ('1:05 - 1:55', '1:05 - 1:55'), ('1:55 - 2:45', '1:55 - 2:45'), ('2:45 - 3:35', '2:45 - 3:35')], default='8:45 - 9:45', max_length=50)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=20)),
                ('courses', models.ManyToManyField(blank=True, to='SchedulerApp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(default=1)),
                ('batch', models.CharField(default='FULL', help_text='FULL | B1 | B2 ...', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SchedulerApp.instructor')),
                ('lab_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SchedulerApp.labroom')),
                ('meeting_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.meetingtime')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='SchedulerApp.generatedtimetable')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.year')),
            ],
        ),
        migrations.AddField(
            model_name='meetingtime',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.year'),
        ),
        migrations.CreateModel(
            name='LabBatchAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(default=1)),
                ('batch', models.CharField(max_length=10)),
                ('session_number', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_assignments', to='SchedulerApp.course')),
                ('instructors', models.ManyToManyField(blank=True, to='SchedulerApp.Instructor')),
                ('lab_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.labroom')),
                ('paired_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_batch_assignments', to='SchedulerApp.course')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.year')),
            ],
        ),
        migrations.AddField(
            model_name='generatedtimetable',
            name='year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.year'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, to='SchedulerApp.Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='lab_rooms',
            field=models.ManyToManyField(blank=True, help_text='Allowed lab rooms for this course', to='SchedulerApp.LabRoom'),
        ),
        migrations.CreateModel(
            name='SpecialPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('Counseling', 'Counseling'), ('Training', 'Training'), ('Sports/Library', 'Sports/Library')], max_length=20)),
                ('hours_per_week', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('continuous_hours', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SchedulerApp.instructor')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.year')),
            ],
            options={
                'unique_together': {('period_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='CourseInstructorAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.course')),
                ('instructors', models.ManyToManyField(blank=True, to='SchedulerApp.Instructor')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.year')),
            ],
            options={
                'unique_together': {('year', 'section_number', 'course')},
            },
        ),
    ]
