# Generated by Django 3.2.25 on 2026-03-29 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0001_initial_correct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedtimetable',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AddField(
            model_name='instructor',
            name='designation',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], default='Assistant Professor', max_length=25),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='evaluators',
            field=models.ManyToManyField(blank=True, help_text='Lab evaluators (Assistant Professors only)', related_name='evaluator_entries', to='SchedulerApp.Instructor'),
        ),
        migrations.AlterField(
            model_name='generatedtimetable',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.year'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_entries', to='SchedulerApp.instructor'),
        ),
    ]
