# Generated by Django 3.2.25 on 2026-02-28 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0002_section_num_class_in_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab')], default='Lecture', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='lab_length',
            field=models.IntegerField(default=0, help_text="Length in hours (e.g., 2 or 3) if it's a lab"),
        ),
        migrations.AddField(
            model_name='section',
            name='year',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='1st Year', max_length=10),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=15),
        ),
        migrations.CreateModel(
            name='SectionCourseAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.instructor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.section')),
            ],
            options={
                'unique_together': {('section', 'course')},
            },
        ),
    ]
