# Generated by Django 3.2.25 on 2026-02-08 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0003_alter_meetingtime_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='department',
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=20)),
                ('courses', models.ManyToManyField(to='SchedulerApp.Course')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.year'),
        ),
    ]
