# Generated by Django 3.2.25 on 2026-02-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0004_auto_20260208_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(default=30)),
            ],
        ),
    ]
