# Generated by Django 3.2.25 on 2026-02-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0005_labroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='continuous_hours',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='hours_per_week',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='course',
            name='is_lab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='labroom',
            name='lab_name',
            field=models.CharField(max_length=50),
        ),
    ]
