# Generated by Django 3.2.25 on 2026-02-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0006_auto_20260210_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='continuous_hours',
            field=models.IntegerField(default=2),
        ),
    ]
