# Generated by Django 3.2.25 on 2026-02-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0008_auto_20260211_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='continuous_hours',
        ),
        migrations.RemoveField(
            model_name='section',
            name='has_saturday',
        ),
        migrations.AddField(
            model_name='course',
            name='max_continuous_hours',
            field=models.IntegerField(default=1),
        ),
    ]
