# Generated by Django 3.2.25 on 2026-02-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0009_auto_20260211_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labroom',
            old_name='capacity',
            new_name='seating_capacity',
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('8:45 - 9:45', '8:45 - 9:45'), ('9:45 - 10:35', '9:45 - 10:35'), ('10:35 - 11:25', '10:35 - 11:25'), ('11:25 - 12:15', '11:25 - 12:15'), ('1:05 - 1:55', '1:05 - 1:55'), ('1:55 - 2:45', '1:55 - 2:45'), ('2:45 - 3:35', '2:45 - 3:35')], max_length=50),
        ),
    ]
