# Generated by Django 3.2.25 on 2026-02-16 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0010_auto_20260212_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtime',
            name='time',
            field=models.CharField(choices=[('8:45 - 9:45', '8:45 - 9:45'), ('9:45 - 10:35', '9:45 - 10:35'), ('10:35 - 11:25', '10:35 - 11:25'), ('11:25 - 12:15', '11:25 - 12:15'), ('12:15 - 1:05', '12:15 - 1:05'), ('1:05 - 1:55', '1:05 - 1:55'), ('1:55 - 2:45', '1:55 - 2:45'), ('2:45 - 3:35', '2:45 - 3:35')], max_length=50),
        ),
        migrations.CreateModel(
            name='CourseInstructorAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.instructor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.section')),
            ],
        ),
    ]
