# Generated by Django 3.2.25 on 2026-02-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0011_auto_20260216_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_lab',
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('THEORY', 'THEORY'), ('LAB', 'LAB'), ('ELECTIVE', 'ELECTIVE')], default='THEORY', max_length=10),
        ),
    ]
