# Generated by Django 3.2.25 on 2026-02-17 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0012_auto_20260216_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('fitness_score', models.FloatField(default=0.0)),
                ('generation_count', models.IntegerField(default=0)),
                ('year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_timetable', to='SchedulerApp.year')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.instructor')),
                ('lab_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.labroom')),
                ('meeting_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.meetingtime')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.section')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='SchedulerApp.generatedtimetable')),
            ],
            options={
                'ordering': ['section', 'meeting_time__day', 'meeting_time__time'],
            },
        ),
    ]
