# Generated by Django 3.2.25 on 2026-02-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0013_generatedtimetable_timetableentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableentry',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
