# Generated by Django 3.2.25 on 2026-02-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0016_auto_20260220_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lab_room',
        ),
        migrations.AddField(
            model_name='course',
            name='lab_rooms',
            field=models.ManyToManyField(blank=True, to='SchedulerApp.LabRoom'),
        ),
    ]
