# Generated by Django 3.2.25 on 2026-02-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0017_auto_20260220_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinstructorassignment',
            name='instructor',
        ),
        migrations.AddField(
            model_name='courseinstructorassignment',
            name='instructors',
            field=models.ManyToManyField(to='SchedulerApp.Instructor'),
        ),
    ]
