# Generated by Django 3.2.25 on 2026-03-05 03:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0018_change_instructor_to_instructors'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('Counseling', 'Counseling'), ('Training', 'Training'), ('Sports/Library', 'Sports/Library')], max_length=20)),
                ('section_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('hours_per_week', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('continuous_hours', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SchedulerApp.instructor')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.year')),
            ],
            options={
                'ordering': ['year', 'section_number', 'period_type'],
                'unique_together': {('period_type', 'year', 'section_number')},
            },
        ),
    ]
