# Generated by Django 3.2.25 on 2026-03-05 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0019_specialperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.instructor'),
        ),
    ]
