# Generated by Django 3.2.25 on 2026-03-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0020_alter_timetableentry_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialperiod',
            options={'ordering': ['year', 'period_type']},
        ),
        migrations.AlterUniqueTogether(
            name='specialperiod',
            unique_together={('period_type', 'year')},
        ),
        migrations.RemoveField(
            model_name='specialperiod',
            name='section_number',
        ),
    ]
