# Generated by Django 3.2.25 on 2026-03-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0021_auto_20260305_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
