# Generated by Django 3.2.25 on 2026-03-07 04:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0022_alter_course_course_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='split_into_batches',
            field=models.BooleanField(default=False, help_text='Split section into batches B1 and B2 (for labs with rotation)'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='batch',
            field=models.CharField(choices=[('B1', 'Batch 1'), ('B2', 'Batch 2'), ('FULL', 'Full Section')], default='FULL', max_length=4),
        ),
        migrations.CreateModel(
            name='LabBatchAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('batch', models.CharField(choices=[('B1', 'Batch 1'), ('B2', 'Batch 2'), ('FULL', 'Full Section')], max_length=4)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15)),
                ('course', models.ForeignKey(limit_choices_to={'split_into_batches': True}, on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.instructor')),
                ('lab_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.labroom')),
                ('paired_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paired_with', to='SchedulerApp.course')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulerApp.year')),
            ],
            options={
                'ordering': ['year', 'section_number', 'course', 'day', 'batch'],
                'unique_together': {('year', 'section_number', 'course', 'batch', 'day')},
            },
        ),
    ]
