# Generated by Django 3.2.25 on 2026-03-07 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0023_auto_20260307_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labbatchassignment',
            options={'ordering': ['year', 'section_number', 'course', 'session_number', 'batch']},
        ),
        migrations.AddField(
            model_name='labbatchassignment',
            name='session_number',
            field=models.IntegerField(default=1, help_text='Session number for rotation (1=first session, 2=second session, etc.)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='labbatchassignment',
            unique_together={('year', 'section_number', 'course', 'batch', 'session_number')},
        ),
        migrations.RemoveField(
            model_name='labbatchassignment',
            name='day',
        ),
    ]
