# Generated by Django 3.2.25 on 2026-03-07 08:37

from django.db import migrations, models
import django.core.validators


def clear_labbatchassignment_data(apps, schema_editor):
    """Clear all LabBatchAssignment data to avoid migration issues"""
    LabBatchAssignment = apps.get_model('SchedulerApp', 'LabBatchAssignment')
    LabBatchAssignment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0024_auto_20260307_1206'),
    ]

    operations = [
        # Clear existing data to avoid schema conflicts
        migrations.RunPython(clear_labbatchassignment_data, migrations.RunPython.noop),
        
        # Drop and recreate the table with correct schema
        migrations.DeleteModel(
            name='LabBatchAssignment',
        ),
        
        migrations.CreateModel(
            name='LabBatchAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('batch', models.CharField(choices=[('B1', 'Batch 1'), ('B2', 'Batch 2'), ('FULL', 'Full Section')], max_length=4)),
                ('session_number', models.IntegerField(default=1, help_text='Session number for rotation (1=first session, 2=second session, etc.)', validators=[django.core.validators.MinValueValidator(1)])),
                ('course', models.ForeignKey(limit_choices_to={'split_into_batches': True}, on_delete=models.deletion.CASCADE, to='SchedulerApp.course')),
                ('instructors', models.ManyToManyField(to='SchedulerApp.Instructor')),
                ('lab_room', models.ForeignKey(on_delete=models.deletion.CASCADE, to='SchedulerApp.labroom')),
                ('paired_course', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='paired_with', to='SchedulerApp.course')),
                ('year', models.ForeignKey(on_delete=models.deletion.CASCADE, to='SchedulerApp.year')),
            ],
            options={
                'ordering': ['year', 'section_number', 'course', 'session_number', 'batch'],
                'unique_together': {('year', 'section_number', 'course', 'batch', 'session_number')},
            },
        ),
    ]
