# Generated by Django 3.2.25 on 2026-03-08 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0025_change_instructor_to_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstructorassignment',
            name='main_instructor',
            field=models.ForeignKey(blank=True, help_text='Primary instructor whose availability determines scheduling', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_courses', to='SchedulerApp.instructor'),
        ),
        migrations.AddField(
            model_name='labbatchassignment',
            name='main_instructor',
            field=models.ForeignKey(blank=True, help_text='Primary instructor whose availability determines scheduling', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_batches', to='SchedulerApp.instructor'),
        ),
        migrations.AlterField(
            model_name='labbatchassignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
