# Generated by Django 3.2.25 on 2026-03-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0026_auto_20260308_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dept_code',
            field=models.CharField(blank=True, help_text='Department code: IT, EC, ME, etc.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='department',
            field=models.CharField(blank=True, help_text='Department code: IT, EC, ME, etc.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='is_evaluator',
            field=models.BooleanField(default=False, help_text='True if this instructor is an evaluator, False if main instructor'),
        ),
    ]
