# Generated by Django 3.2.25 on 2026-03-10 06:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SchedulerApp', '0027_auto_20260308_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='designation',
            field=models.CharField(choices=[('PROF', 'Professor'), ('ASSOC_PROF', 'Associate Professor'), ('ASST_PROF', 'Assistant Professor')], default='ASST_PROF', help_text='Professor, Associate Professor, or Assistant Professor', max_length=20),
        ),
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(blank=True, help_text='Email ID for login', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InstructorPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=15)),
                ('period_1_priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('period_2_priority', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('period_3_priority', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('period_4_priority', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('period_5_priority', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('period_6_priority', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('period_7_priority', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='SchedulerApp.instructor')),
            ],
            options={
                'ordering': ['instructor', 'day'],
                'unique_together': {('instructor', 'day')},
            },
        ),
    ]
