# Generated by Django 3.2.25 on 2026-03-10 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0028_auto_20260310_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='lunch_period',
            field=models.IntegerField(default=5, help_text='Which time slot is lunch break (1-8). 1st year=4 (11:25-12:15), Others=5 (12:15-1:05)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
