# Generated by Django 3.2.25 on 2026-03-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0029_year_lunch_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialperiod',
            name='period_type',
            field=models.CharField(choices=[('Counseling', 'Counseling'), ('Training', 'Training'), ('Sports', 'Sports'), ('Library', 'Library')], max_length=20),
        ),
    ]
