# Generated by Django 3.2.25 on 2026-03-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0030_alter_specialperiod_period_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='split_into_batches',
        ),
        migrations.DeleteModel(
            name='LabBatchAssignment',
        ),
    ]
