# Generated by Django 3.2.25 on 2026-03-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulerApp', '0031_auto_20260325_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableentry',
            name='batch',
        ),
    ]
